#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
easy_admin:
    design:
        form_theme: 'horizontal'

        menu:
            - label: 'Utilisateurs'
            - { entity: 'User', icon: 'users'}

            - label: 'Liens internes'
            - {label: 'Notre site', route: "Accueil", icon: "calendar"}
    entities:
        User:
            class: App\Entity\User
            list:
                title: "Liste des utilisateurs"
                fields:
                    - {property: 'user_name'}
                    - {property: 'password'}
                    - {property: 'pseudo'}
                    - {property: 'email', type: 'email'}
                    - {property: 'role'}
            form:
                title: "Ajout d'un utilisateur"

                fields:
                    - { property: 'pseudo', type: 'text'}
                    - {property: 'password', type: 'text'}
                    - {property: 'email', type: 'email'}
                    - { property: 'role', type: 'choice', type_options:{choices: {'Utilisateur':'ROLE_USER', 'Admin':'ROLE_ADMIN'}}}