security:
    providers:
        mysql:
            entity:
                class: App\Entity\User
                property: userName

    encoders:
        App\Entity\User: plaintext

    firewalls:

        main:
            anonymous: true
            pattern: ^/
            form_login:
                login_path: Connexion   #route vers login

                check_path: Connexion   #route qui va vérifier que le login est ok ou pas
                default_target_path: Accueil

            provider: mysql   #les données proviennent de mysql (def ci dessus)

            logout:
                path:   /deconnexion   #route de deconnexion
                target: /Accueil         #la deconnexion redirige vers

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER     #deux roles pris en comptes, admin > user

    access_control:               #contrôle d'accès
        - { path: ^/admin, roles: ROLE_ADMIN}

